application: metalignus-10
version: 1
runtime: php
api_version: 1
threadsafe: false

handlers:

- url: /scripts
  static_dir: scripts

- url: /css
  static_dir: css

- url: /images
  static_dir: images

- url: /
  script: index.php

- url: /mail.php
  script: mail.php

- url: /(.+)
  script: index.php