application: metalignus-10
version: 3
runtime: php55
api_version: 1
threadsafe: false

handlers:

- url: /favicon.ico
  static_files: favicon.ico
  upload: favicon.ico

- url: /robots.txt
  static_files: robots.txt
  upload: robots.txt

- url: /.*
  script: index.php

- url: /scripts
  static_dir: scripts

- url: /css
  static_dir: css

- url: /images
  static_dir: images

- url: /mail.php
  script: mail.php

  
